server:
  port: 8086

spring:
  application:
    name: notification-service
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: notification-service-group
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: ngocduy6379@gmail.com
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

            

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    com.fashionstore.notification: DEBUG
